# Example docker compose file WITH Postgres service (database + app)
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: streaks_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/streaks_todo
    ports:
      - "9008:9008"
    depends_on:
      - postgres
