services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: streaks_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/streaks_todo
    ports:
      - "9008:9008"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9000:80"
    depends_on:
      - backend
